### ISSUE TITLE
Create Broadcast

### ISSUE THREAD

**Issue by Jpja** [loon3/xcp-tools-js#2]
Is it possible to create a broadcast transaction from a private key?

Would be useful for the Counterparty Foundation Vote
https://forums.counterparty.io/t/announcing-the-start-of-the-counterparty-foundation-voting-period/1006

**Comment by loon3** [comment]
Yes, in the process of putting together the transaction encoding for broadcasts.  You can view the progress here... https://github.com/loon3/xcp-tools-js/blob/master/test/extract_broadcast.html

**Comment by Jpja** [comment]
Cool!
Thanks for making these tools :)

**Comment by loon3** [comment]
https://github.com/loon3/xcp-tools-js/blob/master/test/broadcast_send.html

just implemented broadcasts up to 32 characters (single OP_CHECKMULTISIG output), use this method to sign with a standard private key https://github.com/loon3/xcp-tools-js/issues/1
