### ISSUE TITLE
insight.bitpay.com blocks my IP

### ISSUE THREAD

**Issue by Jpja** [loon3/xcp-tools-js#3]
Cannot make broadcast. After clicking the "Get ... Data" button nothing happens.

I realized that I cannot access https://insight.bitpay.com/api/addr/1BCKatyAbPftqVyVjvANXF9v57kMw2AZEm/utxo from my connection. After I switched to VPN I could access it through a browser, but only after human verification. It thus still did not work in JS.

My workaround is that I copy the json from my browser to a local file, then have the javascript load the local file.

My IP is Latvian, and the only reason I can think of for why it is blocked is that all IPs from this country are blocked. I don't know how many countries they have blocked.

**Comment by Jpja** [comment]
I successfully modified the code to use Blockchain.info's API.

Changes:

``` javascript
var source_html = "https://blockchain.info/unspent?active="+add_from;

/*data.sort(function(a, b) {
            return b.amount - a.amount;
        });  *** May commenting out this lead to a potential bug ???   */

        $.each(data.unspent_outputs, function(i, item) {

             var txid = data.unspent_outputs[i].tx_hash_big_endian; //txid; 
             var vout = data.unspent_outputs[i].tx_output_n; //vout; 
             var script = data.unspent_outputs[i].script; //scriptPubKey; 
             var amount = parseFloat((data.unspent_outputs[i].value)/100000000); //amount
```

**Comment by loon3** [comment]
Nice, I went with Insight initially because Blockchain.info wasn't showing unspent multisig outputs.

The sorting function you commented out is simply to order the utxo's from largest to smallest to keep the size of the tx as small as possible.

**Comment by Jpja** [comment]
Just realized I didn't have to comment it out either. This worked:

``` javascript
        data.unspent_outputs.sort(function(a, b) {
            return b.value - a.value;
        });
```
